name: a11y

channels:
- conda-forge

dependencies:
- python==3.10
- git
- coverage==6.4.4
- jupyter-book==0.13.1
- jupyter-repo2docker==2022.10.0
- jupyter-resource-usage==0.6.1
- jupyterlab-link-share
- matplotlib
- numpy
- plotly
- pyopenssl==22.1.0
- requests==2.28.1
- urllib3==1.26.11
- websockify
- pip
- pip:
  #- -r infra-requirements.txt
  # Upgrade separate from what everyone else uses for now
  # https://github.com/berkeley-dsep-infra/datahub/issues/3693
  - notebook==7.0.0a7
  - jupyterlab==4.0.0a31
  # ###
  # The items below are from infra-requirements, however lab conflicts with the alpha notebook.
  # We disable infre-requirements.txt above and manually enable some of what it provides below.
  # ###
  - nbgitpuller==1.1.0
  - jupyter-resource-usage==0.6.1
  # Matches version in images/hub/Dockerfile
  - jupyterhub==3.1.0
  # - appmode==0.8.0
  # - ipywidgets==7.7.2
  # - jupyter-tree-download==1.0.1
  # - git-credential-helpers==0.2
  # - jupyter-contrib-nbextensions==0.5.1
  # - jupyter_nbextensions_configurator==0.4.1
  # Measure popularity of different packages in our hubs
  # https://discourse.jupyter.org/t/request-for-implementation-instrument-libraries-actively-used-by-users-on-a-jupyterhub/7994?u=yuvipanda
  # - popularity-contest==0.4.1
  # RISE is useful for presentations - see https://github.com/berkeley-dsep-infra/datahub/issues/2527
  # - RISE==5.7.1
  # syncthing for dropbox-like functionality
  # - jupyter-syncthing-proxy==1.0.3
